# ==============================================================================
# fedora-noctalia: Pacotes da Infraestrutura Base do Sistema
# ==============================================================================
# Um pacote por linha. Linhas em branco ou iniciadas com '#' são ignoradas.

# Firmware e Suporte de Hardware
linux-firmware
alsa-firmware

# Gerenciamento de Energia e Bateria
tuned
tuned-ppd
upower
brightnessctl

# Tratamento de Entrada (Touchpad, Teclado, Mouse)
libinput
libinput-utils

# Servidor Multimídia e Áudio (PipeWire)
pipewire
wireplumber
pipewire-pulseaudio
pipewire-alsa

# Conectividade de Rede e Bluetooth
NetworkManager-wifi
bluez
bluez-tools

# Barramento de Sistema e Sessão
dbus-broker
seatd

# Autenticação e Segurança
polkit
mate-polkit
gnome-keyring
libsecret

# Portais e Padrões XDG
xdg-desktop-portal
xdg-desktop-portal-gtk
xdg-user-dirs
xdg-utils

# Gerenciamento de GPU Híbrida (PRIME)
switcheroo-control

# Impressão Universal Sem Driver (IPP Everywhere / Mopria)
cups
cups-filters
ipp-usb
avahi

# Digitalização Sem Driver (eSCL / WSD)
sane-backends
sane-airscan

# Gerenciador de Pacotes Universais Flatpak
flatpak

# Utilitários de Repositório DNF
dnf-plugins-core
