# ==============================================================================
# fedora-noctalia: Aplicações em Flatpak (Flathub)
# ==============================================================================
# Um ID de aplicativo por linha. Linhas em branco ou com '#' são ignoradas.
# Adicione aqui qualquer aplicativo adicional que deseje instalar via Flatpak.

io.github.diegopvlk.Cine
